lang: ko-KR

# Theme
# if your site is deployed on https://<username>.github.io, leave `baseurl` blank.
url: "https://dosuser.github.io"
baseurl: ""

theme: jekyll-theme-chirpy

title: dosuser's blog

tagline: Personal blog about development, spring, and distributed storage

description: >-
  개발, 스프링, 분산 스토리지에 대해 기록하는 개인 블로그.

timezone: Asia/Seoul

github:
  username: dosuser

social:
  name: SHIN DAE YONG
  email: dosuser@naver.com
  links:
    - https://github.com/dosuser
    - https://www.instagram.com/dosuser
    - https://www.facebook.com/daeyong.shin.96

avatar: /assets/images/logo.png

# Site behavior
paginate: 10

theme_mode: dark

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-theme-chirpy
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
  - .sass-cache
  - .jekyll-cache
  - .bundle
  - README.md
